BucStop/Models/Game.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualBasic;
using System.ComponentModel.DataAnnotations;

/*
 * This file contains the Game class, which holds necessary information
 * about the games. Used in GamesController.cs, which has actual instances
 * of each game.
 */

namespace BucStop.Models
{
    public class Game
    {
        //The ID of the game. Starts at 1.
        public int Id { get; set; }

        public GameInfo[] Info { get; set; }

        //The title/name of the game.
        [Required]
        public string Title { get; set; }

        //The javascript file for the game
        [Required]
        [DataType(DataType.MultilineText)]
        public string Content { get; set; }

        //The author(s) of the game.
        [Required]
        public string Author { get; set; }
        //Shows the Date the game was added
        [Required]
        public string DateAdded { get; set; }

        //The description of the game.
        [Required]
        public string Description { get; set; }

        //An explanation of how to play the game, including controls.
        [Required]
        public string HowTo { get; set; }

        //The link to the image of the thumbnail.
        [Required]
        public string Thumbnail { get; set; }

        public int PlayCount { get; set; }

        /*public async Task OnGet([FromServices] MicroClient microClient)
        {
            Info = await microClient.GetGamesAsync  ();
        } */
    }
}

BucStop/Controllers/GamesController.cs
using BucStop.Models;
using BucStop.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Hosting;

/*
 * This file handles the links to each of the game pages.
 */

namespace BucStop.Controllers
{
    [Authorize]
    public class GamesController : Controller
    {
        private readonly MicroClient _httpClient;
        private readonly PlayCountManager _playCountManager;
        private readonly GameService _gameService;

        public GamesController(MicroClient games, IWebHostEnvironment webHostEnvironment, GameService gameService)
        {
            _httpClient = games;
            _gameService = gameService;

            // Initialize the PlayCountManager with the web root path and the JSON file name
            _playCountManager = new PlayCountManager(_gameService.GetGames() ?? new List<Game>(), webHostEnvironment);
        }

        //Takes the user to the index page, passing the games list as an argument
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public async Task<IActionResult> IndexAsync()
        {
            List<Game> games = await GetGamesWithInfo();

            //have to update playcounts here since the we are reading it dynamically now instead of from a static list
            foreach(Game game in games)
            {
                game.PlayCount = _playCountManager.GetPlayCount(game.Id);
            }

            return View(games);
        }

        //Takes the user to the Play page, passing the game object the user wants to play
        public async Task<IActionResult> Play(int id)
        {
            List<Game> games = await GetGamesWithInfo();

            Game game = games.FirstOrDefault(x => x.Id == id);
            if (game == null)
            {
                return NotFound();
            }

            // Increment the play count for the game with the specified ID
            _playCountManager.IncrementPlayCount(id);

            int playCount = _playCountManager.GetPlayCount(id);

            // Update the game's play count
            game.PlayCount = playCount;

            return View(game);
        }

        public async Task<List<Game>> GetGamesWithInfo()
        {
            List<Game> games = _gameService.GetGames();
            GameInfo[] gameInfos = await _httpClient.GetGamesAsync();

            foreach(Game game in games)
            {
                GameInfo info = gameInfos.FirstOrDefault(x => x.Title == game.Title);
                if(info != null)
                {
                    game.Author = info.Author;
                    game.HowTo = info.HowTo;
                    game.DateAdded = info.DateAdded;
                    game.Description = $"{info.Description} \n {info.DateAdded}";
                }
            }

            return games;
        }

        //Takes the user to the deprecated snake page
        public IActionResult Snake()
        {
            return View();
        }

        //Takes the user to the deprecated tetris page
        public IActionResult Tetris()
        {
            return View();
        }
    }
}

BucStop/Controllers/HomeController.cs
using BucStop.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

/*
 * This file has the controllers for everything outside of the games
 * and game-related pages.
 */

namespace BucStop.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly GameService _gameService;

        public HomeController(ILogger<HomeController> logger, GameService games)
        {
            _logger = logger;
            _gameService = games;
        }

        //Sends the user to the deprecated Index page.
        public IActionResult Index()
        {
            return View(_gameService.GetGames());
        }

        //Takes the user to the admin page.
        public IActionResult Admin()
        {
            return View();
        }

        //Takes the user to the privacy policy page.
        public IActionResult Privacy()
        {
            return View();
        }

        //Takes the user to the game criteria page.
        public IActionResult GameCriteria()
        {
            return View();
        }

        //If something goes wrong, this will take the user to a page explaining the error.
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BucStop/Views/Home/Admin.cshtml
@{
    ViewData["Title"] = "Admin Page";
}

<!-- This page will hold the page where admins can interact with the site. Not currently implemented.-->

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <table>
        <tr>
            <td>Admin action 1</td>
            <td>Admin action 2</td>
            <td>Admin action 3</td>
            <td>Admin action 4</td>
        </tr>

    </table>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BucStop/Views/Home/GameCriteria.cshtml
﻿@{
    ViewData["Title"] = "Game Criteria";
}

<!-- Page detailing what criteria a game should meet to be added to the site.-->

<h1>@ViewData["Title"]</h1>

<p>In order to have your game listed on BucStop, your game needs to meet certain criteria: </p>

<ul>
    <li>Must have a name which is not offensive and is less than 50 characters long</li>
    <li>Must have controls which are able to be used on both PC and mobile</li>

        <ul>
            <li>Recommendation is to have it use the arrow keys, as the site will already map swipes to the keys</li>
        </ul>
    <li>Must not contain any offensive material</li>
        <ul>
        <li>Offensive material: material which would give a negative impression of the school</li>
                <ul>
                    <li>Including but not limited to: use of expletives, gore/excessive violence, use of controlled substances, suggestive material, racially insensitive content, illegal material, et cetera</li>
                </ul>
        </ul>
  
    <li>Must be written in Javascript</li>
    <li>Must not have advertisements</li>
    <li>Must not contain any software which could be deemed as malicious</li>
    <li>Must not contain excessive flashing lights or loud sounds</li>
    <li>Must not infringe on any existing copyrighted material</li>
    <li>The file size of the game and all other necessary materials (including images, sounds, et cetera) should not exceed 10MB</li>
    <li>The canvas of the game must be within 640 px by 640 px</li>
    <li>Must not collect user data outside of the bare minimum to save progress in the game</li>
    <li>Any non-javascript files necessary for the game to run must be included in a folder</li>
</ul>
<hr>
<h1>Add your game</h1>
<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSdxu3kg1Cm7Sc7wogaYuRNzbL8fafdTQ9I_nyuCIttKzlg63Q/viewform?embedded=true" width="640" height="1201" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>

BucStop/Views/Home/Games.cshtml
@{
    ViewData["Title"] = "Games Page";
}

<!-- Deprecated. Used to be the games list.-->

<div class="text-center">
    <h1 class="display-4">Games List</h1>
    <a href="../Games/Snake">Snake</a>
    <a href="../Games/Tetris">Tetris</a>
</div>

BucStop/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<!-- Unused file for games list.-->
@{
    List<Game> gamesList = new List<Game>();
    foreach (var game in Model)
    {
        gamesList.Add(game);
        //gamesList.Sort(gamesList.playcount);

    }
}
<div id="demo" class="carousel slide" data-bs-ride="carousel" style="margin-left: 100px; margin-right: 100px;">

    <!-- Indicators/dots -->
    <div class="carousel-indicators">
        @for (int loop = 0; loop < Model.Count; loop++)
        {
            @if(loop == 0)
            {
                <button type="button" data-bs-target="#demo" data-bs-slide-to="@loop" class="active"></button>
            }
            else
            {
                <button type="button" data-bs-target="#demo" data-bs-slide-to="@loop"></button>
            }
            
        }
    </div>

    <!-- Top 3 Games -->
    <h1>top games</h1>
    <!-- Game 1 -->
    <div class="carousel-inner">
        @foreach(var game in gamesList)
        {
            if(game.Id == 1)
            {
                <div class="carousel-item active">
                    <a href="@Url.Action("Play", "Games", new { id = @game.Id })" style="text-decoration: none;">
                        <img src=@game.Thumbnail alt="@game.Title" class="d-block" style="width:100%; height:500%;">
                    </a>
                </div>
            }
            else
            {
                <div class="carousel-item">
                    <a href="@Url.Action("Play", "Games", new { id = @game.Id })" style="text-decoration: none;">
                        <img src=@game.Thumbnail alt="@game.Title" class="d-block" style="width:100%; height:500%;">
                    </a>
                </div>
            }
        }
    </div>

    <!-- Left and right controls/icons -->
    <button class="carousel-control-prev" type="button" data-bs-target="#demo" data-bs-slide="prev">
        <span class="carousel-control-prev-icon"></span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#demo" data-bs-slide="next">
        <span class="carousel-control-next-icon"></span>
    </button>
</div>